#!/usr/bin/env python3
"""Assemble the headless harness runner for the standalone Luau CLI.

Concatenates: shim.lua + each real game module (wrapped as a registered
loader) + driver.lua into a single Luau chunk. The game sources are read
from src/ at build time — there are no copies to drift out of sync.

Usage:
    python3 tools/harness-runner/build_runner.py                  # build only
    python3 tools/harness-runner/build_runner.py --run suite 1000 200
    python3 tools/harness-runner/build_runner.py --run batch 500 Aggressive Defensive
"""

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RUNNER_DIR = Path(__file__).resolve().parent

# Headless module chain only. Replication-phase modules (TelemetryLogger,
# ReplayRecorder, DebugStatePublisher) are excluded: the Replication phase
# never runs under TickManager.Step(true), and DebugStatePublisher requires
# Remotes (Instance creation) at module scope which the shim does not provide.
MODULES = [
    ("ReplicatedStorage/Constants", "src/ReplicatedStorage/Constants.lua"),
    ("ReplicatedStorage/MatchState", "src/ReplicatedStorage/MatchState.lua"),
    ("ReplicatedStorage/LaunchQuality", "src/ReplicatedStorage/LaunchQuality.lua"),
    ("ReplicatedStorage/Stadiums", "src/ReplicatedStorage/Stadiums.lua"),
    ("ReplicatedStorage/Cosmetics", "src/ReplicatedStorage/Cosmetics.lua"),
    ("ReplicatedStorage/BeyParts", "src/ReplicatedStorage/BeyParts.lua"),
    ("ServerScriptService/TickManager", "src/ServerScriptService/TickManager.lua"),
    ("ServerScriptService/MatchInstance", "src/ServerScriptService/MatchInstance.lua"),
    ("ServerScriptService/CollisionClassifier", "src/ServerScriptService/CollisionClassifier.lua"),
    ("ServerScriptService/PhysicsController", "src/ServerScriptService/PhysicsController.lua"),
    ("ServerScriptService/BeyController", "src/ServerScriptService/BeyController.lua"),
    ("ServerScriptService/SpinEvaluator", "src/ServerScriptService/SpinEvaluator.lua"),
    ("ServerScriptService/SimulationHarness", "src/ServerScriptService/SimulationHarness.lua"),
    # Persistence: pure modules only (ProfileStore/StatsRecorder need live Roblox services)
    ("ServerScriptService/Persistence/ProfileSchema", "src/ServerScriptService/Persistence/ProfileSchema.lua"),
    ("ServerScriptService/Persistence/ProfileLogic", "src/ServerScriptService/Persistence/ProfileLogic.lua"),
    # Matchmaking: pure modules only (MatchmakingService needs live Roblox services)
    ("ServerScriptService/Matchmaking/MmrLogic", "src/ServerScriptService/Matchmaking/MmrLogic.lua"),
    ("ServerScriptService/Matchmaking/MatchQueue", "src/ServerScriptService/Matchmaking/MatchQueue.lua"),
]


def build(out_path: Path) -> Path:
    parts = [
        "-- AUTO-GENERATED by tools/harness-runner/build_runner.py — do not edit.\n",
        (RUNNER_DIR / "shim.lua").read_text(),
        "\n",
    ]

    for key, rel_path in MODULES:
        source = (REPO_ROOT / rel_path).read_text()
        parts.append(f'__registerToken("{key}")\n')
        parts.append(f'__defs["{key}"] = function(script)\n{source}\nend\n\n')

    parts.append((RUNNER_DIR / "driver.lua").read_text())

    out_path.write_text("".join(parts))
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="/tmp/bey_harness_runner.lua", help="output path for the assembled chunk")
    parser.add_argument("--luau", default="luau", help="path to the luau CLI binary")
    parser.add_argument("--run", action="store_true", help="execute after building")
    parser.add_argument("prog_args", nargs="*", help="arguments forwarded to the Luau program (mode, counts, ...)")
    args = parser.parse_args()

    out_path = build(Path(args.out))
    print(f"[build_runner] assembled {out_path}", file=sys.stderr)

    if not args.run:
        return 0

    cmd = [args.luau, "-O2", str(out_path)]
    if args.prog_args:
        cmd.append("-a")
        cmd.extend(args.prog_args)
    print(f"[build_runner] exec: {' '.join(cmd)}", file=sys.stderr)
    return subprocess.call(cmd)


if __name__ == "__main__":
    sys.exit(main())
